-- Jeevan core schema.
-- All timestamps are timestamptz in UTC. Enum-like columns are VARCHAR + CHECK
-- (maps cleanly to JPA @Enumerated(STRING) and to Hibernate ddl-auto=validate).

-- ── users ────────────────────────────────────────────────────────────────
-- Login identity is email. Only PATIENT is used by real accounts; DOCTOR/ADMIN
-- are reserved. email_verified defaults TRUE (log-only path); the app sets it
-- FALSE at registration when email verification is enabled.
CREATE TABLE users (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name      VARCHAR(255) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    phone          VARCHAR(32),
    role           VARCHAR(16)  NOT NULL DEFAULT 'PATIENT'
                       CONSTRAINT chk_users_role CHECK (role IN ('PATIENT', 'DOCTOR', 'ADMIN')),
    email_verified BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_email UNIQUE (email)
);

-- ── email_verification_tokens ────────────────────────────────────────────
-- Only exercised on the real-email path. Multiple rows per user over time
-- (resends); only the newest unconsumed, unexpired token is valid.
CREATE TABLE email_verification_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users (id),
    token       VARCHAR(255) NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_evt_token UNIQUE (token)
);
CREATE INDEX idx_evt_user ON email_verification_tokens (user_id);

-- ── doctors ──────────────────────────────────────────────────────────────
-- Seed data only (no doctor login, no admin API).
CREATE TABLE doctors (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    specialty  VARCHAR(128) NOT NULL,
    bio        VARCHAR(512),
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_doctors_specialty ON doctors (specialty);

-- ── doctor_availability ──────────────────────────────────────────────────
-- Recurring weekly windows. Multiple rows per doctor per weekday are allowed
-- (supports a clinic break, e.g. 10:00-13:00 and 17:00-21:00). start_time and
-- end_time are LOCAL clinic times (no zone); interpreted in the clinic timezone.
CREATE TABLE doctor_availability (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id   BIGINT     NOT NULL REFERENCES doctors (id),
    day_of_week VARCHAR(9) NOT NULL
                    CONSTRAINT chk_avail_dow CHECK (day_of_week IN
                        ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
    start_time  TIME       NOT NULL,
    end_time    TIME       NOT NULL,
    CONSTRAINT chk_avail_time CHECK (end_time > start_time)
);
CREATE INDEX idx_avail_doctor_dow ON doctor_availability (doctor_id, day_of_week);

-- ── appointments ─────────────────────────────────────────────────────────
CREATE TABLE appointments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id          BIGINT      NOT NULL REFERENCES users (id),
    doctor_id           BIGINT      NOT NULL REFERENCES doctors (id),
    start_time          TIMESTAMPTZ NOT NULL,
    end_time            TIMESTAMPTZ NOT NULL,
    appointment_status  VARCHAR(16) NOT NULL
                            CONSTRAINT chk_appt_status CHECK (appointment_status IN ('CONFIRMED', 'CANCELLED')),
    notification_status VARCHAR(16) NOT NULL DEFAULT 'PENDING'
                            CONSTRAINT chk_notif_status CHECK (notification_status IN ('PENDING', 'SENT', 'FAILED')),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Authoritative duplicate-booking guarantee: at most one LIVE booking per
-- doctor + slot start. A cancelled row no longer participates, so the slot
-- can be rebooked.
CREATE UNIQUE INDEX uq_appt_doctor_slot_active
    ON appointments (doctor_id, start_time)
    WHERE appointment_status <> 'CANCELLED';

-- Supports dynamic slot generation (doctor + time-range scans).
CREATE INDEX idx_appt_doctor_start ON appointments (doctor_id, start_time);
-- Supports "my appointments" listing and the patient double-booking check.
CREATE INDEX idx_appt_patient_start ON appointments (patient_id, start_time);

-- ── appointment_history ──────────────────────────────────────────────────
-- Append-only audit log; one row per state change (creation, cancellation,
-- notification-status updates). old_status is null on creation.
CREATE TABLE appointment_history (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT       NOT NULL REFERENCES appointments (id),
    old_status     VARCHAR(16),
    new_status     VARCHAR(16)  NOT NULL,
    reason         VARCHAR(255) NOT NULL,
    changed_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_appt_history_appt ON appointment_history (appointment_id);
